name: Build and Deploy Writerside + CodeLabs

on:
  push:
    branches: ["dev"]
  workflow_dispatch:

permissions:
  id-token: write
  pages: write

env:
  INSTANCE: 'Writerside/modo-docs'
  ARTIFACT: 'webHelpMODO-DOCS2-all.zip'
  DOCKER_VERSION: '241.15989'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install claat tool
      - name: Install claat tool
        run: go install github.com/googlecodelabs/tools/claat@latest
        env:
          GOPATH: ${{ runner.temp }}/go

      # Ensure claat is in PATH
      - name: Add claat to PATH
        run: echo "${{ runner.temp }}/go/bin" >> $GITHUB_PATH

      # Step to Generate CodeLab HTML Files
      - name: Generate CodeLabs content
        run: |
          mkdir -p codelabs-generated
          claat export -o codelabs-generated codelabs/workshop/workshop-codelab.md || exit 1

      # Verify that CodeLabs files were generated
      - name: List generated CodeLabs files
        run: ls -la codelabs-generated

      # Writerside build step
      - name: Build docs using Writerside Docker builder
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: ${{ env.INSTANCE }}
          artifact: ${{ env.ARTIFACT }}
          docker-version: ${{ env.DOCKER_VERSION }}

      # Unzip the Writerside artifact
      - name: Unzip Writerside artifact
        run: |
          mkdir -p dir
          unzip -O UTF-8 -qq artifacts/${{ env.ARTIFACT }} -d dir

      # Verify Writerside files were unzipped correctly
      - name: Verify unzipped Writerside content
        run: ls -la dir

      # Combine CodeLabs and Writerside output
      - name: Copy CodeLabs to Writerside output
        run: |
          if [ -d "codelabs-generated" ] && [ "$(ls -A codelabs-generated)" ]; then
            cp -R codelabs-generated/* dir/
          else
            echo "No CodeLabs content generated."
            exit 1
          fi

      # Verify CodeLabs content was copied into Writerside output
      - name: Verify combined content in Writerside output
        run: ls -la dir

      # Save combined Writerside + CodeLabs artifact
      - name: Save combined artifact with Writerside and CodeLabs
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: dir
          retention-days: 7

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Requires build job results
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: docs

      # Set up for GitHub Pages deployment
      - name: Setup Pages
        uses: actions/configure-pages@v4.0.0

      # Upload to GitHub Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: dir

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.4