name: Detekt Check
run-name: Running Detekt checks
on:
  push:
    branches:
      - "dev"
  pull_request:
    branches:
      - "dev"
jobs:
  detekt-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: "Detekt"
        run: ./gradlew detektAll
        continue-on-error: false

