name: Detekt Check
run-name: Running Detekt checks
on:
  push:
    branches:
      - "dev"
  pull_request:
    branches:
      - "dev"
jobs:
  detekt-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: "Run Detekt"
        run: ./gradlew detektAll
        continue-on-error: false

      - name: "Upload Detkt sarif results"
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: build/reports/detekt/detekt.sarif
          category: detekt

